### ISSUE TITLE
Every time I run fast film grain I get OOM error.

### ISSUE THREAD

**Issue by PoLTheToWeR** [vrgamegirl19/comfyui-vrgamedevgirl#2]
It would be good to update the node so that we can choose whether the film grain is applied with the CPU or GPU.

**Comment by driqeks** [comment]
I have same issue with fast film grain on large resolutions or long videos. Please add a batch size parameter to the node for setting how many frames to do at once.

**Comment by vrgamegirl19** [comment]
🎞️ Fast Film Grain (FastFilmGrain)
Add controllable, grayscale or color grain for cinematic texture.
➕ Now includes a batch_size setting to reduce out-of-memory (OOM) issues on long or high-res videos. If you have a strong GPU, try batch_size = 8. If you hit OOM, lower the value (e.g., to 4 or 2).

🎨 Color Match to Reference (ColorMatchToReference)
Align image tones to a reference image using LAB color matching.
➕ Also includes a batch_size setting to help manage VRAM usage. Start at 8 if your GPU allows — lower it if you get OOM errors.

**Comment by driqeks** [comment]
> Nodes have been updated with a batch size input.
> 
> 🎞️ Fast Film Grain (FastFilmGrain) Add controllable, grayscale or color grain for cinematic texture. ➕ Now includes a batch_size setting to reduce out-of-memory (OOM) issues on long or high-res videos. If you have a strong GPU, try batch_size = 8. If you hit OOM, lower the value (e.g., to 4 or 2).

Thanks! It works. Can you increase the max batch more please? I want to do at least 100 frames at once and currently the max is 64.
